doctrine:
    dbal:
        default_connection: default

        connections:
            default:
                driver: pdo_pgsql
                host: '%env(string:DB_HOST)%'
                port: '%env(string:DB_PORT)%'
                dbname: '%env(string:DB_NAME)%'
                user: '%env(string:DB_USER)%'
                password: '%env(string:DB_PASSWORD)%'
                charset: UTF8

        types:
            contact_id: AristekSystems\TestTask\Doctrine\Type\ContactIdType
            project_id: AristekSystems\TestTask\Doctrine\Type\ProjectIdType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware

        mappings:
            AristekSystems\TestTask\Entity\:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/mapping'
                prefix: 'AristekSystems\TestTask\Entity'
                alias: AristekSystems\TestTask
